# Generated by Django 4.0.5 on 2022-07-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_subscribers_remove_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
