# Generated by Django 4.0.5 on 2022-09-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_categorytype_en_post_categorytype_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoryType_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryType_ru',
        ),
    ]
